interface CONFIG {
  PORT: number;
  NODE_ENV: string;
  LOG_LEVEL: string;
  REDIS_URL: string;
  JWT_SECRET: string;
  RESEND_API_KEY: string;
  OPENROUTER_API_KEY: string;

  AWS_REGION: string;
  AWS_S3_BUCKET: string;

  CASHFREE_CLIENT_ID: string;
  CASHFREE_CLIENT_SECRET: string;

  FRONTEND_ORIGIN: string;
  BACKEND_ORIGIN: string;
}

export const config: CONFIG = {
  PORT: Number(Bun.env.PORT!),
  NODE_ENV: Bun.env.NODE_ENV!,
  LOG_LEVEL: Bun.env.LOG_LEVEL!,
  REDIS_URL: Bun.env.REDIS_URL!,
  JWT_SECRET: Bun.env.JWT_SECRET!,
  RESEND_API_KEY: Bun.env.RESEND_API_KEY!,
  OPENROUTER_API_KEY: Bun.env.OPENROUTER_API_KEY!,

  AWS_REGION: Bun.env.AWS_REGION!,
  AWS_S3_BUCKET: Bun.env.AWS_S3_BUCKET!,

  CASHFREE_CLIENT_ID: Bun.env.CASHFREE_CLIENT_ID!,
  CASHFREE_CLIENT_SECRET: Bun.env.CASHFREE_CLIENT_SECRET!,

  FRONTEND_ORIGIN: Bun.env.FRONTEND_ORIGIN!,
  BACKEND_ORIGIN: Bun.env.BACKEND_ORIGIN!,
};
